AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    Default: 'dev'
    AllowedValues:
    - dev
    - test
    - stage
    - prod
  GitSHA:
    Type: String
    Default: ''
    Description: SHA of git commit
  DeployBucket:
    Type: String
    Default: 'sps-build-deploy'
    Description: S3 bucket used for deployable objects

Outputs:
  PDCommenterArn:
    Description: "Arn of the pd-commenter lambda function"
    Value: !GetAtt 'CommenterFunction.Arn'
    Export:
      Name: !Join [ "-", [ !Ref 'Environment', pd-commenter-lambda-arn ] ]
  PDCommenterArn2:
    Description: "Arn of the pd-commenter lambda function"
    Value: !GetAtt 'CommenterFunction.Arn'
    Export:
      Name: !Sub "${AWS::StackName}:pd-commenter-lambda-arn"


Resources:
  CommenterFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: pd-commenter.create_incident_note
      Runtime: python2.7
      CodeUri:
          Bucket: !Ref 'DeployBucket'
          Key: !Sub "${Environment}/sre/oaf/utility/oaf-pd-commenter/${GitSHA}/deployment.zip"
      Description: "Posts a note in PagerDuty"
      MemorySize: 128
      Timeout: 30
      Tracing: Active
      Environment:
        Variables:
          environ: !Ref Environment
      Policies:
        - Statement:
            Effect: Allow
            Action: 'kms:Decrypt'
            Resource:
            - Fn::ImportValue:
                !Sub "${Environment}-credstash:CredstashKeyArn"
        - Statement:
            Effect: Allow
            Action: ['dynamodb:Query', 'dynamodb:GetItem']
            Resource:
            - Fn::ImportValue:
                !Sub "${Environment}-credstash:CredstashTableArn"
            Condition:
              ForAllValues:StringLike:
                dynamodb:LeadingKeys:
                  - 'sre.oaf.utility.pd-commenter.username'
                  - 'sre.oaf.utility.pd-commenter.password'
        - Statement:
            Effect: "Allow"
            Action:
              - "xray:PutTraceSegments"
              - "xray:PutTelemetryRecords"
            Resource: "*"

  CloudWatchAlarm:
    Type: AWS::CloudFormation::Stack
    Properties:
        TemplateURL: "https://s3.amazonaws.com/sps-build-deploy/sre/oaf/utilty/nested-cloudwatch-alarm.yml"
        TimeoutInMinutes: 2
        Parameters:
          FunctionName: !Ref CommenterFunction
